---
- name: Assignment 2
  hosts: web
  tasks:
  - name: Install the latest version of httpd
    ansible.builtin.dnf:
      name: httpd
      state: latest

  - name: Create an index.html file
    ansible.builtin.template:
      src: /home/sysadm/lab/mytemplates/index.j2
      dest: /var/www/html/index.html

  - name: Enable the httpd service and start
    ansible.builtin.systemd:
      name: httpd.service
      state: started
      enabled: true

  - name: Allow httpd in firewalld
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
